# Generated by Django 2.2.7 on 2020-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200520_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='staticfiles/imagepost'),
        ),
    ]
