# Generated by Django 2.2.7 on 2020-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200520_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='foodblog\\staticfiles\\imagespost'),
        ),
    ]
