# Generated by Django 2.2.7 on 2020-05-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200520_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiltle',
            new_name='title',
        ),
    ]
