# Generated by Django 2.2.7 on 2020-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
